# Command prefix
commandPrefix: "!"

# Channel for welcome messages. Use null to disable welcome messages.
welcomeChannel: "general" 

# Channel for goodbye messages. Use null to disable goodbye messages.
goodbyeChannel: "general"

# Role to assign new guild members. Use null to assign no role.
joinRole: "member"

# Prefix to designate color roles.
colorPrefix: "color."
