# Authentication token for the bot application:
# If null, the "token" property of auth.json will be used.
token: null

# Command prefix
commandPrefix: "!"

# Channel for welcome messages. Use null to disable welcome messages.
welcomeChannel: "general" 

# Channel for goodbye messages. Use null to disable goodbye messages.
goodbyeChannel: "general"

# Channel for ban messages. Use null to disable ban messages.
banChannel: "general"

# Role to assign new guild members. Use null to assign no role.
joinRole: "member"

# Prefix to designate color roles. Use null to disable the colors feature.
colorPrefix: "color."
