module.exports = [
    "{user} has left the server.",
    ":crab: {user} IS GONE! :crab:",
    "{user} has left the game.",
    "{user} tried to swim in lava.",
    "{user} fell from a high place.",
    "Goodbye, {user}.",
    "{user} watch out! OH GOD THEY HAVE AIRPODS IN THEY CAN'T HEAR US.",
    "{user} has committed tax fraud.",
    "servers[n-1].remove_member('{user}');",
    "Have you seen my friend {user}? {user}!",
    "I'm better than {user} so I should do the review.",
    "From: {user}\nTo: servers[n-1]\nSubject: Please remove me from this mailing list",
    "{user} got thrown in the saarlac pit.",
    "{user} FLEW TO JAPAN TO SING ABBA IN A BIG COLD RIVER",
    "{user} missed the event cutoff.",
    "{user} is out like a light\n(like a light)\nlike a light",
    "I don't like you {user}. Nothing personal, kid. But you must leave now.",
    "{user} got ran over by a tunnel cart.",
    "Why my {user} not working lol"
];