module.exports = [
    "{user} joined the server. UmiYays in the chat!",
    "{user} joined the server today - cake and ice cream are on its way!",
    "{user} should listen to HERE I AM from Re:CREATORS",
    "{user} has arrived just in time for epic gamer moments",
    "{user} joined the server. Verifying security clearance.",
    "{user} is our 1,000,000th visitor. Like for a free iPad.",
    "{user} has joined the miku gang.",
    "{user} has arrived with gold as a silver bonus",
    "{user} isn't so great? Are you kidding me?",
    "{user} in the hou\n\n\n\n\n\n\n\nse tonight",
    "You know {user}, from Discord?",
    "Get up, get up, what's that in the sky? Could it be? It's {user}.",
    "You know who it is. Coming round again. You want a dose of this right now it's {user}.",
    "Let's all give {user} a warm welcome!",
    "{user} has now entered the bottom left friendship corner no kill pls 'u'",
    "Roses are red,\n{user} walks into a bar,\ntypes !scout11;\nHAHA, NO UR",
    ":wave: {user} :wave:",
    "{user} has brought all the scuttlebugs together for one big jamboree.",
    "I tap these 3 mountains to cast {user}, pass the turn.",
    "Dear {user}, I wrote you, but you still ain't calling.",
    "Ah, {user}, just the person I've been looking for. Please make a roast beef and a turkey.",
    "Ah {user}, welcome. I hope you have prepared for an unforgettable luncheon!",
    "The {user} bus is comin' and everybody's jumpin'",
    "This welcome message sucks, can {user} think of a better one?",
    "servers[n-1].add_member('{user}');",
    "WHAT? That's not {user}. That's some person from like Attack on Titan or whatever.",
    "Is this {user}? Are you {user}? What the grand is a {user}?!",
    "{user} into the {user}verse",
    "What you're seeing now is my normal state.\nThis is a super {user}. And this.\nThis is what is known as a super {user} that has ascended above a super {user}.\nOr, you could just call this a super {user} two.",
    "And in conclusion, we have found {user}DB to be an excellent database for our website. Any questions?",
    "●●●{user} is typing...",
    "Right before your eyes\nWatch us multiply\nCome to claim our rights\nIts {user}",
    "Guess who's back?\nBack again\n{user}'s back\nTell a friend",
    "Bokolo P, Esshi, Chokyoshi, Futitsukeshi, {user}! Amazing new server members from all across Discord.",
    "Hello Everyone, I’m Scott, President of Domino’s Pizza! Have you heard of {user}? Today I'd like to announce a new collaborative project featuring {user}: Domino's App featuring {user}!"
];